### ISSUE TITLE
Osmosis polkachu node can be null

### ISSUE THREAD

**Issue by baktun14** [ovrclk/cosmos-omnibus#372]
https://github.com/ovrclk/cosmos-omnibus/blob/master/run.sh#L136

Hey, for some reason the polkachu snapshot url can be null and it just crashes the download. I was trying to deploy with the default config or with `SNAPSHOT_POLKACHU=1`. Got it working by explicity specify the url and disabling the polkachu variable.

**Comment by baktun14** [comment]
Also, it seems like once the snapshot is downloaded `https://snapshots.polkachu.com/snapshots/osmosis/osmosis_7268027.tar.lz4` it just crashes and restarts the download from scratch in infinite loop.

**Comment by andy108369** [comment]
> Hey, for some reason the polkachu snapshot url can be null and it just crashes the download.

Just hit the same but with sifchain.
Running with `DEBUG=2` led me to:

```
[node-0] ++ curl -Ls http://polkachu.com/api/v1/chains/sifchain/snapshot
[node-0] + export POLKACHU_SNAPSHOT=null
```

and the reason:

```
$ curl -Ls http://polkachu.com/api/v1/chains/sifchain/snapshot
{"success":false,"reason":"Temporarily unavailable. Please contact hello@polkachu.com to get your IP whitelisted to access this endpoint."}
```

> it just crashes and restarts the download from scratch in infinite loop.

I have not tried the osmosis, but with sifchain am hitting this issue:
https://github.com/ovrclk/cosmos-omnibus/issues/373

**Comment by baktun14** [comment]
Probably the same issue, thx

**Comment by andy108369** [comment]
@baktun14 

Oh, I see the issue with the osmosis, it's that they went to `v13.1.0` 2 days ago.
I'm going to bump it now and will update here.

Refs.

https://www.mintscan.io/osmosis/blocks/7241500
https://www.mintscan.io/osmosis/proposals/370
https://raw.githubusercontent.com/osmosis-labs/osmosis/main/networks/osmosis-1/upgrades/v13/v13_binaries.json
https://github.com/osmosis-labs/osmosis/releases/tag/v13.1.0

**Comment by andy108369** [comment]
Made few fixes to `cosmos-omnibus` and cut `v0.3.17` release:
- osmosis is now `v13.1.0` (since Thursday)
- report on a missing polkachu snapshot (it now prints a message and waits for `10 mins` before retrying)
- recreate `priv_validator_state.json` if is missing (related to https://github.com/tendermint/tendermint/issues/8389 )

Once this [job](https://github.com/ovrclk/cosmos-omnibus/actions/runs/3666182457/jobs/6197740175) finishes (in about 10 mins), please give `ghcr.io/ovrclk/cosmos-omnibus:v0.3.17-osmosis-v13.1.0` a shot.

You'll likely need to ask Polkachu for whitelisting the IP or use another snapshot. Or state-sync, though Polkachu don't offer it for osmosis it [seems](https://polkachu.com/state_sync/) ...

**Comment by baktun14** [comment]
I just tried and now get this
![image](https://user-images.githubusercontent.com/15185355/206880030-59c4cc0a-bfd5-4500-9b31-ab996bfc6550.png)

**Comment by andy108369** [comment]
> I just tried and now get this ![image](https://user-images.githubusercontent.com/15185355/206880030-59c4cc0a-bfd5-4500-9b31-ab996bfc6550.png)

What snapshot are you using? Could you please share your settings, so I can give it a shot?

**Comment by baktun14** [comment]
```
services:
  node:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.3.17-osmosis-v13.1.0
    env:
      - MONIKER=my-moniker-1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/chain.json
      - P2P_POLKACHU=1
      #- STATESYNC_POLKACHU=1
      #- SNAPSHOT_POLKACHU=1
      #- SNAPSHOT_WASM_PATH=wasm
      - SNAPSHOT_URL=https://snapshots.polkachu.com/snapshots/osmosis/osmosis_7268027.tar.lz4
```
