### ISSUE TITLE
I cannot run this image successfully

### ISSUE THREAD

**Issue by Glacier-Luo** [ovrclk/cosmos-omnibus#92]
When i run akash node on akash, there is nothing log and maybe crashed.
When i run on my machine, it always exit with code 7 or 35, and sometimes, it doesn't do anything, and it doesn't show up.
Only once, it seems to have run successfully.
![PCZKA~(63`VHEA5HNOQKOCB](https://user-images.githubusercontent.com/30594509/146494376-cbf404d9-2a93-44e9-b763-c69d1cfe24e2.png)
I read the tutorials in the documentation that the first startup in the document seems to have failed. Is it starting repeatedly to expect a normal run?

**Comment by tombeynon** [comment]
Strange - I've not seen anything like that before. I'm not sure what changes you've made to the docker-compose/Dockerfile so could you try a docker-compose.yml like this?

```
version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.17-akash-v0.12.1
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/ovrclk/net/master/mainnet/meta.json
    volumes:
      - ./node-data:/root/.akash
```

**Comment by Glacier-Luo** [comment]
``` bash
➜  akashnode docker-compose up --force-recreate
Pulling node_1 (ghcr.io/ovrclk/cosmos-omnibus:v0.0.17-akash-v0.12.1)...
v0.0.17-akash-v0.12.1: Pulling from ovrclk/cosmos-omnibus
004f1eed87df: Already exists
3637e3316c04: Already exists
a2fa0fc5e617: Pull complete
bcaedcb50aa5: Pull complete
4dbdf3f0fe81: Pull complete
Digest: sha256:c2f84d797c89626cfee53f5d8197cdaa3853b863ce5e9dcc78289541c45f7e11
Status: Downloaded newer image for ghcr.io/ovrclk/cosmos-omnibus:v0.0.17-akash-v0.12.1
Creating akashnode_node_1_1 ... done
Attaching to akashnode_node_1_1
akashnode_node_1_1 exited with code 35
➜  akashnode cat docker-compose.yml
version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.17-akash-v0.12.1
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/ovrclk/net/master/mainnet/meta.json
    volumes:
      - ./node-data:/root/.akash
```

But the test in severa hours ago, it runs successfully.Sometims maybe it is ok.
![image](https://user-images.githubusercontent.com/30594509/146534319-d6142007-632a-4ccf-9d62-d7501c6afe2b.png)
I don't know why, may be a problem about network?But yesterday i tried to deploy it on akash, It also failed.

**Comment by tombeynon** [comment]
Ah you have no disk space left - that's why the containers are failing in both examples. The Snapshot restore for Akash involves downloading and extracting about 300GB of data so I would make sure you have enough disk space to do that. Let me know if that solves it for you and I'll close this issue.

**Comment by Glacier-Luo** [comment]
Yes, i know that, but only when it runs successful, it would be no disk space.In most cases, it just exits.

**Comment by Glacier-Luo** [comment]
I'm also trying to deploy it to akash, but it's just like that.
![image](https://user-images.githubusercontent.com/30594509/146537408-2594c8b9-e9ad-4931-a8c9-5215b6bb8200.png)
![image](https://user-images.githubusercontent.com/30594509/146537451-290bb886-e56b-4de0-ac6a-2b8ffc2218ed.png)
``` yaml
---
version: '2.0'

services:
  node:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.17-akash-v0.12.1
    env:
      - MONIKER=GlacierLuo
      - CHAIN_JSON=https://raw.githubusercontent.com/ovrclk/net/master/mainnet/meta.json
      - SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/akash/snapshot.json
      - MINIMUM_GAS_PRICES=0.025uakt
      - FASTSYNC_VERSION=v2
    expose:
      - port: 26657
        as: 80
        accept:
          - rpc.supernaut.ddns.net
          - rpc.akash.glacierluo.com
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 1317
        as: 80
        accept:
          - api.supernaut.ddns.net
          - api.akash.glacierluo.com
        to:
          - global: true
      - port: 9090
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 350Gi
  placement:
    dcloud:
      pricing:
        node:
          denom: uakt
          amount: 1000

deployment:
  node:
    dcloud:
      profile: node
      count: 1
```
![image](https://user-images.githubusercontent.com/30594509/146537547-17c344f2-587b-48a4-93cb-5a0a64933d23.png)
![image](https://user-images.githubusercontent.com/30594509/146537567-82d35b15-974d-4f86-bac6-53bc8119752c.png)

**Comment by tombeynon** [comment]
We download and extract the snapshot at the same time so it will start to use a lot of disk space as soon as it starts downloading the snapshot. 

The SDL you gave has two different ports exposed as `80`, which I would expect to cause some issues. Otherwise I don't actually see any errors there and the deployment is active? Did you submit your manifest to the provider?

**Comment by Glacier-Luo** [comment]
```yaml
---
version: "2.0"

services:
  node:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.17-akash-v0.12.1
    env:
      - MONIKER=my-moniker-1
      - CHAIN_JSON=https://raw.githubusercontent.com/ovrclk/net/master/mainnet/meta.json
      - SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/akash/snapshot.json
      - MINIMUM_GAS_PRICES=0.025uakt
      - FASTSYNC_VERSION=v2
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 350Gi
  placement:
    dcloud:
      pricing:
        node:
          denom: uakt
          amount: 1000

deployment:
  node:
    dcloud:
      profile: node
      count: 1
```
I am trying to deploy like this, but it still crashes and restarts.
Expose a port to 80 only means that's a http service, i am sure that the deployment is active, and the provider has got the manifest, otherwise it cannot expose the port and bind the domain.
